apiVersion: apps/v1
kind: Deployment
metadata:
  name: sign-in-deployment
  labels:
    app: sign-in
spec:
  replicas: 1
  selector:
    matchLabels:
      app: sign-in
  template:
    metadata:
      labels:
        app: sign-in
    spec:
      containers:
      - name: sign-in
        image: /sign-in
        ports:
        - containerPort: 4000

---
apiVersion: v1
kind: Service
metadata:
  name: sign-in-service
spec:
  type: NodePort
  selector:
    app: sign-in
  ports:
    - protocol: TCP
      port: 4000
      targetPort: 4000
      nodePort: 30002